apiVersion: v1
kind: Secret
metadata:
  name: mongologin
type: Opaque
data:
  dburl: Zm9yX3RoZV9sb3ZlX29mX2dvZF9kb19ub3RfY29tbWl0X3RoaXNfZmlsZV93aXRoX3JlYWxfaW5mb3JtYXRpb24=
  username: Zm9yX3RoZV9sb3ZlX29mX2dvZF9kb19ub3RfY29tbWl0X3RoaXNfZmlsZV93aXRoX3JlYWxfaW5mb3JtYXRpb24=
  password: Zm9yX3RoZV9sb3ZlX29mX2dvZF9kb19ub3RfY29tbWl0X3RoaXNfZmlsZV93aXRoX3JlYWxfaW5mb3JtYXRpb24=
