kind: BuildConfig
apiVersion: v1
metadata:
  name: "vuefront" 
spec:
  runPolicy: Serial
  triggers:
  - type: ImageChange
  - type: ConfigChange
  source:
    images:
    - from:
        kind: ImageStreamTag
        name: vuefront-artifact:latest
      paths:
      - sourcePath: /opt/app-root/src/dist
        destinationDir: "."
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx-112-rhel7:latest
  output:
    to:
      kind: ImageStreamTag
      name: vuefront:latest
